### ISSUE TITLE
Is this an example?

### ISSUE THREAD

**Issue by metanerd** [end-of-game/cloudunit#214]
cloudunit/cu-compose/cu-traefik/certs/traefik.key

this is the private key, or an example for a private key? When it is an example then don't mind me.
I am still wondering how you did this with the gitlab certs though :(

**Comment by zepouet** [comment]
Hello,

It is an example for a private key. We don't use TLS between Gitlab and Traefik. 
TLS is only between external and Traefik.

Do you know Traefik ? We can help you about CloudUnit installation. Please free to ask questions.

Best regards,
Nicolas

**Comment by metanerd** [comment]
I am actually not installing CloudUnit, sorry. I was just searching for examples with gitlab and traefik, because I am having some problems mounting the ssl certs, as usual :) I will close this then.
